ARG JAVA_VERSION=11

FROM gradle:7-jdk${JAVA_VERSION} as builder

RUN apt update \
    && apt install -y rsync xz-utils

ADD https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.xz /tmp/

RUN cd /tmp/ \
    && tar xvf node-v18.18.0-linux-x64.tar.xz \
    && rsync -arvc node-v18.18.0-linux-x64/* /usr/local/

FROM gradle:7-jdk${JAVA_VERSION}

COPY --from=builder /usr/local/ /usr/local/
